name:                stack-test
version:             0.1.0.0
github:              "githubuser/stack-test"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

description:         Please see the README on GitHub at <https://github.com/githubuser/stack-test#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  stack-test-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
